<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17664" started-at="2020-05-09T12:04:07 IST" finished-at="2020-05-09T12:04:24 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17664" started-at="2020-05-09T12:04:07 IST" finished-at="2020-05-09T12:04:24 IST">
      <class name="tests.rest.TC001_CreateIncident">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="beforeSuite" is-config="true" duration-ms="842" started-at="2020-05-09T12:04:06 IST" finished-at="2020-05-09T12:04:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setValues()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="setValues" is-config="true" duration-ms="0" started-at="2020-05-09T12:04:07 IST" finished-at="2020-05-09T12:04:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="beforeClass" is-config="true" duration-ms="3" started-at="2020-05-09T12:04:07 IST" finished-at="2020-05-09T12:04:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="beforeMethod" is-config="true" duration-ms="10" started-at="2020-05-09T12:04:07 IST" finished-at="2020-05-09T12:04:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="createIncident(java.io.File)[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="createIncident" duration-ms="17572" started-at="2020-05-09T12:04:07 IST" data-provider="fetchData" finished-at="2020-05-09T12:04:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[.\data\TC001.JSON]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportRequest(HTMLReporter.java:96)
at lib.rest.RESTAssuredBase.verifyResponseTime(RESTAssuredBase.java:168)
at tests.rest.TC001_CreateIncident.createIncident(TC001_CreateIncident.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createIncident -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-05-09T12:04:24 IST" finished-at="2020-05-09T12:04:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:tests.rest.TC001_CreateIncident@1fc2b765]" name="afterSuite" is-config="true" duration-ms="426" started-at="2020-05-09T12:04:24 IST" finished-at="2020-05-09T12:04:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- tests.rest.TC001_CreateIncident -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
